/**
 * Service Catalog Seed Script
 * 
 * Populates the database with all available Florida filing services
 */

import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

const services = [
  // ============================================
  // FORMATION SERVICES
  // ============================================
  {
    name: 'LLC Formation',
    slug: 'llc-formation',
    orderType: 'LLC_FORMATION',
    category: 'FORMATION',
    shortDescription: 'Form a new Florida Limited Liability Company',
    longDescription: 'Start your Florida LLC with our comprehensive formation service. We handle all paperwork and filing with the Florida Department of State.',
    serviceFee: 100,
    stateFee: 125,
    totalPrice: 225,
    rushFeeAvailable: true,
    rushFee: 50,
    entityTypes: ['LLC'],
    processingTime: '5-7 business days',
    filingMethod: 'online',
    isActive: true,
    isPopular: true,
    isFeatured: true,
    displayOrder: 1,
    icon: '🏢',
    keywords: ['llc', 'formation', 'start business', 'limited liability company'],
  },
  {
    name: 'Corporation Formation',
    slug: 'corporation-formation',
    orderType: 'CORP_FORMATION',
    category: 'FORMATION',
    shortDescription: 'Form a new Florida Corporation',
    longDescription: 'Incorporate your business in Florida. We prepare and file your Articles of Incorporation with the state.',
    serviceFee: 100,
    stateFee: 70,
    totalPrice: 170,
    rushFeeAvailable: true,
    rushFee: 50,
    entityTypes: ['CORPORATION'],
    processingTime: '5-7 business days',
    filingMethod: 'online',
    isActive: true,
    isPopular: true,
    isFeatured: true,
    displayOrder: 2,
    icon: '🏛️',
    keywords: ['corporation', 'incorporation', 'c-corp', 's-corp'],
  },
  {
    name: 'Fictitious Name Registration (DBA)',
    slug: 'fictitious-name-registration',
    orderType: 'FICTITIOUS_NAME_REGISTRATION',
    category: 'FORMATION',
    shortDescription: 'Register a "Doing Business As" name',
    longDescription: 'Register a fictitious name (DBA) to operate your business under a different name than your legal entity name.',
    serviceFee: 50,
    stateFee: 50,
    totalPrice: 100,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['DBA'],
    processingTime: '3-5 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: true,
    isFeatured: true,
    displayOrder: 3,
    icon: '📝',
    keywords: ['dba', 'fictitious name', 'trade name', 'doing business as'],
  },
  
  // ============================================
  // ANNUAL COMPLIANCE
  // ============================================
  {
    name: 'LLC Annual Report',
    slug: 'llc-annual-report',
    orderType: 'LLC_ANNUAL_REPORT',
    category: 'ANNUAL_COMPLIANCE',
    shortDescription: 'File your LLC annual report',
    longDescription: 'Keep your LLC in good standing by filing the required annual report with the Florida Department of State. Due by May 1st each year.',
    serviceFee: 50,
    stateFee: 138.75,
    totalPrice: 188.75,
    rushFeeAvailable: true,
    rushFee: 25,
    entityTypes: ['LLC'],
    processingTime: 'Instant (online filing)',
    filingMethod: 'online',
    isActive: true,
    isPopular: true,
    isFeatured: false,
    displayOrder: 10,
    icon: '📊',
    keywords: ['annual report', 'llc', 'compliance', 'yearly filing'],
  },
  {
    name: 'Corporation Annual Report',
    slug: 'corporation-annual-report',
    orderType: 'CORP_ANNUAL_REPORT',
    category: 'ANNUAL_COMPLIANCE',
    shortDescription: 'File your corporation annual report',
    longDescription: 'Maintain your corporation\'s good standing with the state. Annual reports are due by May 1st for profit corporations.',
    serviceFee: 50,
    stateFee: 150,
    totalPrice: 200,
    rushFeeAvailable: true,
    rushFee: 25,
    entityTypes: ['CORPORATION'],
    processingTime: 'Instant (online filing)',
    filingMethod: 'online',
    isActive: true,
    isPopular: true,
    isFeatured: false,
    displayOrder: 11,
    icon: '📊',
    keywords: ['annual report', 'corporation', 'compliance'],
  },
  {
    name: 'Fictitious Name Renewal',
    slug: 'fictitious-name-renewal',
    orderType: 'FICTITIOUS_NAME_RENEWAL',
    category: 'ANNUAL_COMPLIANCE',
    shortDescription: 'Renew your DBA registration',
    longDescription: 'Fictitious names must be renewed every 5 years. We handle the renewal filing to keep your DBA active.',
    serviceFee: 40,
    stateFee: 50,
    totalPrice: 90,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['DBA'],
    processingTime: '3-5 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 12,
    icon: '🔄',
    keywords: ['dba renewal', 'fictitious name renewal'],
  },
  
  // ============================================
  // REINSTATEMENT
  // ============================================
  {
    name: 'LLC Reinstatement',
    slug: 'llc-reinstatement',
    orderType: 'LLC_REINSTATEMENT',
    category: 'ANNUAL_COMPLIANCE',
    shortDescription: 'Reinstate a dissolved LLC',
    longDescription: 'Restore your administratively dissolved LLC to active status. Includes filing fees and back annual reports.',
    serviceFee: 150,
    stateFee: 600,
    totalPrice: 750,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['LLC'],
    processingTime: '10-15 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 20,
    icon: '🔄',
    keywords: ['reinstatement', 'llc', 'dissolved', 'restore'],
  },
  {
    name: 'Corporation Reinstatement',
    slug: 'corporation-reinstatement',
    orderType: 'CORP_REINSTATEMENT',
    category: 'ANNUAL_COMPLIANCE',
    shortDescription: 'Reinstate a dissolved corporation',
    longDescription: 'Bring your administratively dissolved corporation back to active status.',
    serviceFee: 150,
    stateFee: 600,
    totalPrice: 750,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['CORPORATION'],
    processingTime: '10-15 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 21,
    icon: '🔄',
    keywords: ['reinstatement', 'corporation', 'dissolved'],
  },
  
  // ============================================
  // AMENDMENTS
  // ============================================
  {
    name: 'LLC Amendment',
    slug: 'llc-amendment',
    orderType: 'LLC_AMENDMENT',
    category: 'AMENDMENTS',
    shortDescription: 'Amend your LLC Articles of Organization',
    longDescription: 'Make changes to your LLC\'s name, purpose, duration, or other provisions in the Articles of Organization.',
    serviceFee: 75,
    stateFee: 25,
    totalPrice: 100,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['LLC'],
    processingTime: '5-7 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 30,
    icon: '✏️',
    keywords: ['amendment', 'llc', 'change name', 'update'],
  },
  {
    name: 'Corporation Amendment',
    slug: 'corporation-amendment',
    orderType: 'CORP_AMENDMENT',
    category: 'AMENDMENTS',
    shortDescription: 'Amend your Articles of Incorporation',
    longDescription: 'Update your corporation\'s Articles of Incorporation to reflect changes in name, stock structure, or other provisions.',
    serviceFee: 75,
    stateFee: 25,
    totalPrice: 100,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['CORPORATION'],
    processingTime: '5-7 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 31,
    icon: '✏️',
    keywords: ['amendment', 'corporation', 'articles'],
  },
  {
    name: 'Registered Agent Change',
    slug: 'registered-agent-change',
    orderType: 'REGISTERED_AGENT_CHANGE',
    category: 'AMENDMENTS',
    shortDescription: 'Change your registered agent or office',
    longDescription: 'Update your registered agent or registered office address on file with the state.',
    serviceFee: 50,
    stateFee: 25,
    totalPrice: 75,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['LLC', 'CORPORATION', 'LP'],
    processingTime: '3-5 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: true,
    isFeatured: false,
    displayOrder: 32,
    icon: '👤',
    keywords: ['registered agent', 'change agent', 'update address'],
  },
  
  // ============================================
  // DISSOLUTION
  // ============================================
  {
    name: 'LLC Dissolution',
    slug: 'llc-dissolution',
    orderType: 'LLC_DISSOLUTION',
    category: 'DISSOLUTION',
    shortDescription: 'Dissolve your Florida LLC',
    longDescription: 'Officially close your LLC and remove it from the Florida business registry.',
    serviceFee: 75,
    stateFee: 25,
    totalPrice: 100,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['LLC'],
    processingTime: '5-7 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 40,
    icon: '🚪',
    keywords: ['dissolution', 'llc', 'close business', 'terminate'],
  },
  {
    name: 'Corporation Dissolution',
    slug: 'corporation-dissolution',
    orderType: 'CORP_DISSOLUTION',
    category: 'DISSOLUTION',
    shortDescription: 'Dissolve your Florida corporation',
    longDescription: 'Formally dissolve your corporation and terminate its existence with the state.',
    serviceFee: 75,
    stateFee: 25,
    totalPrice: 100,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['CORPORATION'],
    processingTime: '5-7 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 41,
    icon: '🚪',
    keywords: ['dissolution', 'corporation', 'close business'],
  },
  
  // ============================================
  // CERTIFICATES
  // ============================================
  {
    name: 'Certificate of Status',
    slug: 'certificate-of-status',
    orderType: 'CERTIFICATE_OF_STATUS',
    category: 'CERTIFICATES',
    shortDescription: 'Get proof of good standing',
    longDescription: 'Obtain an official Certificate of Status showing your entity is in good standing with the state.',
    serviceFee: 25,
    stateFee: 5,
    totalPrice: 30,
    rushFeeAvailable: true,
    rushFee: 15,
    entityTypes: ['LLC', 'CORPORATION', 'LP'],
    processingTime: '1-2 business days',
    filingMethod: 'online',
    isActive: true,
    isPopular: true,
    isFeatured: false,
    displayOrder: 50,
    icon: '📜',
    keywords: ['certificate of status', 'good standing', 'certificate'],
  },
  {
    name: 'Name Reservation',
    slug: 'name-reservation',
    orderType: 'NAME_RESERVATION',
    category: 'CERTIFICATES',
    shortDescription: 'Reserve a business name',
    longDescription: 'Reserve your desired business name for 120 days while you prepare to form your entity.',
    serviceFee: 25,
    stateFee: 35,
    totalPrice: 60,
    rushFeeAvailable: false,
    rushFee: 0,
    entityTypes: ['LLC', 'CORPORATION'],
    processingTime: '3-5 business days',
    filingMethod: 'mail',
    isActive: true,
    isPopular: false,
    isFeatured: false,
    displayOrder: 51,
    icon: '🔖',
    keywords: ['name reservation', 'reserve name'],
  },
];

async function main() {
  console.log('🌱 Seeding service catalog...\n');

  for (const service of services) {
    console.log(`Creating service: ${service.name}`);
    
    await prisma.service.upsert({
      where: { slug: service.slug },
      update: service,
      create: service,
    });
  }

  console.log(`\n✅ Successfully seeded ${services.length} services!`);
}

main()
  .catch((e) => {
    console.error('Error seeding services:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

